### ISSUE TITLE
StatefulSetsのレプリカ数がスライドのシナリオと不整合

### ISSUE THREAD

**Issue by hi-rose39** [kubernetes-sapporo-for-beginners/hands-on#17]
シナリオではreplicas1でデプロイ→2に変更となっているが、初期状態から2になっている。
https://github.com/kubernetes-sapporo-for-beginners/hands-on/blob/5aff88ea06fcfe6aaf2e7520b754ce8c675641d5/Step1-ApplicationDeployment/statefulsets/020-statefulsets.yaml#L7

**Comment by h-r-k-matsumoto** [comment]
replicas=2に技としてます。資料の方直し忘れているので、資料を修正します。
